# Generated by Django 6.0.3 on 2026-05-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_barcode_image_product_barcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode_code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
